# Site settings
title: "Code fog"
description: >
  The more you know, the more you don't know.

author: Code fog
email: at20s@sina.com
twitter_username: liqitry
github_username: liqimore

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.codefog.com" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id: codefog

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:title

sass:
    style: compressed

exclude: [vendor]
